spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/datajiang?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: unionlabs
      password: 123456
      filters: log4j,wall,mergeStat